services:
  consultaserviceDB: 
    image: postgres:16
    container_name: pgcontainer
    restart: always
    environment: 
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: consultaservicedb
    ports:
      - 5435:5432
    volumes:
      - ./dbdata:/var/lib/postgresql