services:
#   api:
#     container_name: enfermeiro-container
#     image: enfermeiro-service-container:latest
#     environment:
#         - ASPNETCORE_ENVIRONMENT=docker
#         - ASPNETCORE_URLS=http://+:5091
#     ports:
#         - "5091:5091"
#     depends_on:
#         pgenfermeiroserver:
#             condition: service_healthy

  pgenfermeiroserver:
    image: postgres:16
    container_name: pgenfermeiroserver
    ports:
        - "5433:5433"
    volumes:
        - "./Database/pg_data:/var/lib/postgresql/data"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: admin
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U postgres"]
        interval: 10s
        timeout: 5s
        retries: 5

